完善了控件分类页面以及接受修改意见
avaloniachina/Documentation pull request #10
Opened 2022-12-14 13:47 UTC by Luoyingliang

1. View Activation 翻译中，我在查阅英文版文档之后，我觉得这里的Activation指的是激活的机制而不是激活的行为。
2. Access the UI Thread，在翻阅英文版文档，我感觉源文档提供的教程主要是针对如何在UI线程上进行操作

2022-12-14 15:51 UTC, zdpcdt requested changes

2022-12-14 15:51 UTC, zdpcdt commented on docs/authoring-controls/README.md
> +{% content-ref url="types-of-control.md" %} [types-of-control.md](https://github.com/AvaloniaUI/Documentation/blob/master/docs/authoring-controls/types-of-control.md) {% endcontent-ref %}
这里链接的地址指向文档，不要指向github

2022-12-14 15:51 UTC, zdpcdt commented on SUMMARY.md
> +  * [在Raspberry Pi上运行你的应用（使用Raspbian Lite）](guides/deep-dives/running-your-app-on-a-raspberry-pi-with-raspbian-lite.md)
```suggestion
  * [在树莓派上运行你的应用（使用Raspbian Lite）](guides/deep-dives/running-your-app-on-a-raspberry-pi-with-raspbian-lite.md)
```

2022-12-14 15:51 UTC, zdpcdt commented on SUMMARY.md
> +  * [在Raspberry Pi上运行你的应用](guides/deep-dives/running-your-app-on-a-raspberry-pi.md)
```suggestion
  * [在树莓派上运行你的应用](guides/deep-dives/running-your-app-on-a-raspberry-pi.md)
```

2022-12-14 15:51 UTC, zdpcdt commented on SUMMARY.md
> +  * [Xaml介绍](guides/basics/introduction-to-xaml.md)
```suggestion
  * [XAML 介绍](guides/basics/introduction-to-xaml.md)
```

2022-12-14 15:51 UTC, zdpcdt commented on docs/authoring-controls/README.md
> +学习如何创建自定义控件，
```suggestion
学习如何创建自定义控件。
```

2022-12-14 15:51 UTC, zdpcdt commented on docs/authoring-controls/types-of-control.md
> +`TemplatedControl`s 是最长使用的在多个程序之间共享的通用控件。他们初始状态下没有外观,这意味着它们可以为不同的主题、程序重新设计外观。  Avalonia定义的大多数标准控件都属于这一类。
```suggestion
`TemplatedControl`是最常使用的、能在多个程序之间共享的通用控件。它们在初始状态下没有外观，这意味着它们可以为不同的主题和应用程序重新设计外观。Avalonia定义的大多数标准控件都属于这一类。
```

2022-12-14 15:51 UTC, zdpcdt commented on docs/authoring-controls/types-of-control.md
> +{% hint style="info" %}  在 WPF/UWP你需要继承自 Control 类型来创建一个新的控件, 但是在Avalonia 你需要继承自`TemplatedControl.` {% endhint %}
```suggestion
{% hint style="info" %}  在 WPF/UWP 中你需要从 Control 类型继承来创建一个新的控件，但是在 Avalonia 中你需要从`TemplatedControl`继承。 {% endhint %}
```

2022-12-14 15:51 UTC, zdpcdt commented on docs/authoring-controls/types-of-control.md
> +{% hint style="info" %} 如果你想在一个单独的文件中，为你创建的`TemplatedControl`提供一个`Style`,记住在你的程序中使用 [`StyleInclude`](https://docs.avaloniaui.net/docs/styling/styles) 导入你的文件. {% endhint %}
```suggestion
{% hint style="info" %} 如果你想在一个单独的文件中为你创建的`TemplatedControl`提供一个`Style`，别忘记在你的应用程序中使用 [`StyleInclude`](https://docs.avaloniaui.net/docs/styling/styles) 导入这个文件。{% endhint %}
```

2022-12-14 15:51 UTC, zdpcdt commented on docs/authoring-controls/types-of-control.md
> +`Control`是用户界面的基础 - 它们通过重写  `Visual.Render`  来使用几何图形来绘制自己。渲染方法。 像`TextBlock` 和 `Image` 这样的控件就属于这一类.
```suggestion
`Control`是用户界面的基础 - 它们通过重写 `Visual.Render` 方法来使用几何图形绘制自己。像`TextBlock` 和 `Image` 这样的控件就属于这一类。
```

2022-12-14 15:51 UTC, zdpcdt commented on docs/authoring-controls/types-of-control.md
> +{% hint style="info" %} 在 WPF/UWP你需要继承自 FrameworkElement 类型来创建一个新的控件, 但是在Avalonia 你需要继承自 `Control.` {% endhint %}
```suggestion
{% hint style="info" %} 在 WPF/UWP 中你需要从 FrameworkElement 类型继承来创建一个新的控件，但是在 Avalonia 你需要从 `Control` 继承。 {% endhint %}
```

2022-12-15 05:14 UTC, Luoyingliang commented
已经按照建议改进

2022-12-15 05:37 UTC, zdpcdt approved these changes

2022-12-15 05:39 UTC, merged